### ISSUE TITLE
[SO2] Risposte errate alle domande 122 e 43

### ISSUE THREAD

**Issue by ENDERZOMBI102** [appinfosapienza/so-un-bot#18]
La domanda di SO2 n.122
```
122. SI consideri il seguente frammento di codice:

int x, y, nread;
float xx, yy;
nread=scanf("%d %d",&x, &y);
printf("x=%d, y=%d, nread=%d \n",x,y,nread);
printf("xx=%f, yy=%f, nread=%d \n",xx,yy,nread);
nread=scanf("%f %f",&xx, &yy);

Assumiamo che, in fase di esecuzione, la prima scanf legge su stdin la sequenza
1 w
Quale sara' il valore di nread dopo l'esecuzione della seconda scanf?
1. 0
2. 2
3. dipende dall'input letto su stdin dalla seconda scanf
```
Ha la risposta sbagliata ( 1 ), mentre dovrebbe esser la 3, dato che `nread` e' rimpiazzato dalla lettura della seconda `scanf()`

Mentre la 43:
43. Consideriamo queste due line di codice
1. printf("main:%s\n",strerror(errno));
2. perror("main");
Quali delle seguenti affermazioni è corretta?

1. Producono stringhe diverse e la prima la invia su stdout mentre la seconda su stderr.
2. Inviano la stessa stringa su stdout
3. producono la stessa stringa ma la 1 la invia su stdout, mentre la 2 su stderr

Da come corretta la 3, mentre quella effettivamente corretta e' la 1.
![image](https://github.com/appinfosapienza/so-un-bot/assets/36399599/1fb57874-d319-424d-aedc-36f0453f5fda)

**Comment by notherealmarco** [comment]
Per quanto riguarda la 122, la prima scanf consuma solo il primo numero (1) e lo spazio, per cui nreads = 1. Al termine della prima scanf quindi nello stdin rimane il solo carattere "w".

La seconda scanf non consuma la w, per cui nreads = 0 e quindi la risposta 1 è corretta.

Al termine del frammento di codice quindi nep stdin continua a rimanere il carattere "w".


Riguardo la 43 invece, sono d'accordo con te che le stringhe siano diverse per la presenza dello spazio (nel caso di perror), però all'esame il professore ha sempre dato come corretta quella risposta.

**Comment by notherealmarco** [comment]
Per la 43 in realtà non so come comportarmi, perché c'è anche un altro caso (domanda 20) che è l'esatto contrario: il bot segna quella corretta, ma all'esame ha dato corretta una risposta errata.

Potrei per entrambe dare la corretta come corretta sul bot, e aggiungere una nota nel testo della domanda con quella che ha dato come corretta all'esame, può aver senso?

**Comment by ENDERZOMBI102** [comment]
mi sembra la soluzione migliore
