### ISSUE TITLE
Domanda 74. 11.  questionario su so2

### ISSUE THREAD

**Issue by gpelisset** [appinfosapienza/so-un-bot#29]
Ho guardato la domanda 74. 11 del questionario so2 per la quale era richiesta una segnalazione.
Chiaramante la risposta 1) e' falsa in quanto, ad esempio SIGCONT, non termina il processo
Per la risposta 2, non e' possibile ridefinire il comportamento di alcuni segnali come SIGKILL. Infatti https://man7.org/linux/man-pages/man2/signal.2.html dice espressamente

> The signals SIGKILL and SIGSTOP cannot be caught or ignored.

Per la risposta 3, il manuale https://man7.org/linux/man-pages/man2/kill.2.html dice

>    For a process to have permission to send a signal, it must either
>    be privileged (under Linux: have the CAP_KILL capability in the
>    user namespace of the target process), or the real or effective
>    user ID of the sending process must equal the real or saved set-
>    user-ID of the target process.  In the case of SIGCONT, it
>    suffices when the sending and receiving processes belong to the
>    same session.  (Historically, the rules were different; see
>   NOTES.)

Quindi sembra essere possibile per qualsiasi processo di un utente inviare un qualsiasi segnale ad un processo dello stesso utente.

Per esclusione la 4 (Nessuna delle altre affermazioni è vera) e' falsa. 

Forse andrebbe cambiata la risposta?

**Comment by notherealmarco** [comment]
ha senso, correggo
