### ISSUE TITLE
Questione relativa ai .png nelle domande

### ISSUE THREAD

**Issue by Deco71** [appinfosapienza/so-un-bot#6]
Come chiedeva @simonesestito, i .png presenti in alcune domande (tipo 0621_22) servono a qualcosa o possono essere eliminati tranquillamente? @notherealmarco

**Comment by Deco71** [comment]
Fixed with #7

**Comment by notherealmarco** [comment]
Rispondo per i futuri lettori: no, non servono, il bot al momento accetta solo URL.
